
</div>
</div>
</div>
</div>

<div class="footer container-fluid" style="background-color: orange; ">
    <div class="row ">
        <div class="modal-footer">

            <div class="row">
                <div class="col-md-4">
                    <h4>
                        <p class="text-center" style="padding: 2px;"><strong>Licenciatura em Educação do Campo -
                                LEDOC</strong></p>
                        <hr/>
                        <p class="text-center"><strong><span class="glyphicon glyphicon-tags"></span></strong> Campus
                            Canguaretama / IFRN - BR-101, Km 160. S/N. - Areia Branca, Canguaretama - RN, 59190-000.</p>
                        <p class="text-center"><strong></strong></p>
                        <p class="text-center"><strong><span class="glyphicon glyphicon-earphone"></span></strong></p>
                        <p class="text-center"><strong><span class="glyphicon glyphicon-envelope"></span></strong> lic.ledoc.cang@gmail.com</p>
                    </h4>
                </div>
                <div class="col-md-4">

                </div>
                <div class="col-md-4">
                    <h4>
                        <a href="<?=PAF.DIR?>equipe"><p class="text-center" style="padding: 2px;">
                                <strong>Desenvolvedores</strong></p></a>
                        <hr/>
                        <p class="text-center"><strong>Luiz Fernandes de Oliveira</strong></p>
                        <p class="text-center"><span class="glyphicon glyphicon-envelope"></span>
                            luiz.fernades@academico.ifrn.edu.br</p>
                        <p class="text-center"><strong>Gilmar Lima</strong></p>
                        <p class="text-center"><span class="glyphicon glyphicon-envelope"></span>
                            gilmar.lima@academico.ifrn.edu.br</p>
                    </h4>
                </div>
            </div>

        </div>
    </div>
    <div class="radio">
        <div class="row">
            <a href="index.php"><img class="img-responsive" id="" src="<?=PAF?>/public/img/BG02.png" style="width:100%"></a>
        </div>
    </div>
</div>

</body>
</html>
