<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title><?= TITLE ?></title>
    <link rel="shortcut icon" href="<?= PAF ?>/public/img/favicon/favicon.ico">
    <link rel="stylesheet" href="<?= PAF ?>/public/css/style.css">
    <link rel="stylesheet" href="<?= PAF ?>/public/css/bootstrap.css">
    <link rel="stylesheet" href="<?= PAF ?>/public/css/bootstrap.min.css">
    <script src="<?= PAF ?>/public/js/bootstrap.min.js"></script>
    <script src="<?= PAF ?>/public/js/bootstrap.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Almendra SC' rel='stylesheet'>
    <style>@import url('https://fonts.googleapis.com/css?family=Playfair+Display|Ropa+Sans');</style>

</head>

<body>
<div class="container-fluid text-center bg-info">
    <!--   style="margin: -9px 4%;box-shadow: 0px 0px 20px rgba(0,0,0,.6);"   -->
    <div class="text-center bg-info" id="top">
        <!--========================= ADCIONANDO MENU SUPERIOR ============================-->
        <div class="bg-info ">
            <div class="row" style="background-color: white;">
                <a href="index.php"><img class="img-responsive" id="" src="<?= PAF ?>/public/img/icon_siteledoc.png"
                                         style="width: 700px; margin: 0px auto;"></a>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 center-block">
                <!--=======================ADCIONANDO MENU LATERAL ===================================-->
                <div class="col-md-12 center-block thumbnail">
                    <div class="col-md-2">

                        <div class='row'>
                            <a href="<?= PAF . DIR ?>admin/login">
                                <button type="button" class="btn btn-block btn-success"><h5>ACESSO RESTRITO</h5>
                                </button>
                            </a>
                        </div>

                    </div>
                    <?php $menus = MENUS;
                    if (isset($menus)): foreach ($menus as $menu => $value): ?>
                        <div class="col-md-2">
                            <div class='row'>
                                <a href="<?= PAF . DIR . $menu ?>">
                                    <button class="btn btn-primary btn-block dropdown-toggle" type="button">
                                        <h5><?= $value ?></h5>
                                    </button>
                                </a>
                            </div>
                        </div>
                    <?php endforeach; endif; ?>
                    <div class="col-md-2">
                        <div class='row'>
                            <div class="btn-group btn-block dropup">
                                <button class="btn btn-primary btn-block dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                    <h5>MAIS</h5>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <?php $submenus = SUBMENUS;
                                    if (isset($submenus)): foreach ($submenus as $submenu => $value): ?>
                                        <div class="dropdown-item">
                                            <div class='row'>
                                                <a href="<?= PAF . DIR . $submenu ?>">
                                                    <button class="btn btn-primary btn-block dropdown-toggle"
                                                            type="button">
                                                        <h5><?= $value ?></h5>
                                                    </button>
                                                </a>
                                            </div>
                                        </div>
                                    <?php endforeach; endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>