<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="<?= PAF ?>/public/admin/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?= PAF ?>/public/admin/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="<?= PAF ?>/public/admin/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?= PAF ?>/public/admin/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="<?= PAF ?>/public/admin/plugins/iCheck/square/blue.css">

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="bg-success">
<div class="container">
    <div class="row">
    <!--================================ JANELA MODAL PARA CADASTRO DO ADMINISTRADOR ======================================-->

    <div class="col-md-8 col-md-offset-2 thumbnail">
        <div class="thumbnail center-block">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times; SAIR</span></button>
                <h4 class="modal-title" id="exampleModalLabel">ÁREA DE CADASTRO</h4>
            </div>
            <div class="modal-header">
                <?php if (isset($erro)): ?>
                    <div class="alert alert-danger active"><?= isset($erro) ? $erro : '' ?></div>
                <?php endif; ?>
                <?php if (isset($sucesso)): ?>
                    <div class="alert alert-success active"><?= isset($sucesso) ? $sucesso : '' ?></div>
                <?php endif; ?>
            </div>
            <div class="modal-header">
                <div class="bg-danger">
                    <h4>ATENÇÃO: </h4>

                        <h5 class="text-center" >O cadastro é restrito para pessoas
                            autorizadas
                            pela instituição, caso não tenha autorização, não tente efetuá-lo.</h5>

                </div>

            </div>
        </div>
        <div class="modal-body">
            <form action="<?= PAF.DIR ?>admin/cadastro" method="post">
                <div class="container-fluid thumbnail">
                    <div class="col-md-2 radio"><strong>Nome:</strong></div>
                    <div class="col-md-10"><input type="text" class="form-control" name="nome">
                    </div>
                </div>
                <div class="container-fluid thumbnail">
                    <div class="col-md-2 radio"><strong>E-mail:</strong></div>
                    <div class="col-md-10"><input type="email" class="form-control" name="email">
                    </div>
                </div>
                <div class="container-fluid thumbnail">
                    <div class="col-md-2 radio"><strong>Matricula:</strong></div>
                    <div class="col-md-10"><input type="text" class="form-control" name="matricula">
                    </div>
                </div>

                <div class="container-fluid thumbnail">
                    <div class="col-md-2 radio"><strong>Senha:</strong></div>
                    <div class="col-md-10"><input type="password" class="form-control" name="senha">
                    </div>
                </div>
                <div class="container-fluid thumbnail">
                    <div class="col-md-2 radio"><strong>Repita a senha:</strong></div>
                    <div class="col-md-10"><input type="password" class="form-control"
                                                  name="resenha">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
            </form>
        </div>
    </div>

    <!--======================== FIM DA JANELA MODAL =======================-->

    <!--==================== FIM DA JANELA MODAL PARA CADASTRO ==============================-->
</div>
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="<?= PAF ?>/public/admin/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="<?= PAF ?>/public/admin/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="<?= PAF ?>/public/admin/plugins/iCheck/icheck.min.js"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>
