<div class="container">
    <div class="thumbnail">
        <h1><p class="text-center">CORPO DOCENTE</p></h1>
    </div>


    <div class="container center-block thumbnail">
        <div>
            <div class="row">
                <h3>
                    <div class="col-sm-6 thumbnail">
                        <strong>Nome</strong>
                    </div>
                    <div class="col-sm-6 thumbnail">
                        <strong>E-mal</strong>
                    </div>
                </h3>
            </div>
        </div>
        <div>
            <h4>
                <div class="row">
                    <div class="col-sm-6 ">

                    </div>
                    <div class="col-sm-6 ">

                    </div>
                </div>
            </h4>
        </div>
        <hr/>

    </div>

</div>