<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Licenciatura em Educação do Campo - IFRN/ Campus Canguaretama</title>
    <link rel="shortcut icon" href="<?=PAF.DIR?>public/img/favicon/favicon.ico">
    <link rel="stylesheet" href="<?=PAF.DIR?>public/css/style.css">
    <link rel="stylesheet" href="<?=PAF.DIR?>public/css/bootstrap.css">
    <link rel="stylesheet" href="<?=PAF.DIR?>public/css/bootstrap.min.css">
</head>

<body class="bg-info">
<div class="container-fluid text-center bg-info">
    <div class="container-fluid text-center bg-info" style="margin: -9px 4%;box-shadow: 0px 0px 20px rgba(0,0,0,.6);">
        <h4>
            <div class="thumbnail">
                <h1><p class="text-center">DESENVOLVEDORES</p></h1>
            </div>

            <div class="container thumbnail">
                <div class="container-fluid text-center bg-info">
                    <div class="col-md-12 col-sm-12 col-xs-12 col-lg-12 center-block thumbnail">
                        <div class="radio">
                            <div class="thumbnail col-md-12">
                                <div class="media">
                                    <div class="media-left col-md-3 col-lg-3 col-sm-3 col-xs-3">
                                        <img src="<?=PAF.DIR?>public/img/equipe/luiz.jpg" class="media-object" style="width:130px;">
                                    </div>
                                    <div class="media-body">
                                        <h1>Luiz Fernandes de Oliveira</h1>
                                        <p class="text-center"><strong>E-mail: luiz.fernandes@academico.ifrn.edu.br</strong></p>
                                        <p class="text-center"><strong>WhatsApp: (84) 98119-5936</strong></p>
                                        <p class="text-center"><strong>Curriculo Lattes: </strong><a href="http://lattes.cnpq.br/3830771163451285" target="_blank">http://lattes.cnpq.br/3830771163451285</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="radio">
                            <div class="thumbnail col-md-12">
                                <div class="media">
                                    <div class="media-left col-md-3 col-lg-3 col-sm-3 col-xs-3">
                                        <img src="<?=PAF.DIR?>public/img/equipe/gilmar.jpeg" class="media-object" style="width:130px">
                                    </div>
                                    <div class="media-body">
                                        <h1>Gilmar Lima</h1>
                                        <p class="text-center"><strong>E-mail: gilmar.lima@academico.ifrn.edu.br</strong></p>
                                        <p class="text-center"><strong>WhatsApp: (84) 98137-7782</strong></p>
                                        <p class="text-center"><strong>Curriculo Lattes: </strong><a href="http://lattes.cnpq.br/8407113239058393" target="_blank">http://lattes.cnpq.br/8407113239058393</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </h4>

    </div>

</div>

</body>
</html>
