
    <div class="content-wrapper">
        <div class="row">
        	<div class="col-md-8 col-md-offset-2">
        		<h1>Novo post</h1>

        		<?php if(isset($error)): ?>
        			<div class="alert-danger"><?= $error ?></div>
        		<?php endif; ?>
        		<div class="panel panel-default">
        			<div class="panel-heading">
        				Formulario do post
        			</div>

        			<div class="panel-body">

        				<form action="<?= PATH ?>/admin/posts/add" method="post" enctype="multipart/form-data">
						  <div class="form-group">
						    <label for="titulo">Titulo</label>
						    <input type="text" class="form-control" id="titulo" placeholder="Digite o título" name="titulo">
						  </div>

						  <div class="form-group">
						    <label for="descricao">Descricao</label>
						    <textarea name="descricao" class="form-control" cols="30" rows="10" placeholder="descricao"></textarea>
						  </div>
						  
						  <button type="submit" class="btn btn-primary">Cadastrar</button>
						</form>
        			</div>
        		</div>
        	</div>
        </div>

    </div>
    