<div class="thumbnail">
    <h1><p class="text-center">SOBRE O CURSO</p></h1>
</div>
<div class="container">
    <div class="thumbnail container" style="padding: 20px;">
        <h2>
            <p class="bg-success">O Curso Superior de Licenciatura em Educação do Campo</p>
            <p class="text-justify" style="text-indent: 4em">Na modalidade presencial, refere-se à formação docente para
                atuar na educação básica
                na área de Ciências Humanas e Sociais ou Matemática. Tem como objetivo geral formar professores para
                atuar:</p>
            <br/>
            <p class="text-justify">1) em escolas do campo, nos anos finais do ensino fundamental e no ensino médio, nas
                áreas de Ciências Humanas e Sociais ou Matemática, bem como na gestão de processos educativos de tais
                escolas;</p>
            <p class="text-justify">2) em espaços não-escolares no campo, respeitando e valorizando a diversidade
                presente nas comunidades.</p>
            <br/>
            <p class="text-justify" style="text-indent: 4em">Após a integralização dos componentes curriculares que
                compõem a matriz curricular,
                inclusive a realização da Prática Profissional do Curso Superior de Licenciatura em Educação do Campo
                será conferido ao estudante o Diploma de Licenciado em Educação do Campo, com habilitação em Ciências
                Humanas e Sociais ou em Matemática.</p>

        </h2>
        <h2>
            <p class="bg-success"><strong>Carga Horária</strong></p>
            <p class="text-justify">3.314 horas</p>
        </h2>
        <h2>
            <p class="bg-success"><strong>Duração</strong></p>
            <p class="text-justify">4 anos</p>
        </h2>
        <h2>
            <p class="bg-success"><strong>Resolução de Criação</strong></p>
            <p class="text-justify">Deliberação Nº 04/2016-CONSEPEX, de 22 de fevereiro de 2016</p>
        </h2>
    </div>
</div>
<div class="thumbnail">
    <h1><p class="text-center">DOCUMENTOS</p></h1>
</div>
<div class="container">
    <div class="thumbnail container">
        <div class="row">
            <div class="col-md-4">
                <h2>
                    <p class="bg-success">Projéto Pedagógico do Curso(PPC)</p>
                    <p style="border: solid black 1px">2016 - 2018 <a href="<?= PAF ?>/public/doc/PPP.pdf"><img
                                    src="<?= PAF ?>/public/img/logo_pdf.png" style="width: 20px;">baixar</a></p>
                </h2>
            </div>
            <div class="col-md-4">
                <h2>
                    <p class="bg-success">Matriz Curricular Habilitação Matemática</p>
                    <p style="border: solid black 1px">2016 - 2018 <a href="<?= PAF ?>/public/doc/matematica.pdf"><img
                                    src="<?= PAF ?>/public/img/logo_pdf.png" style="width: 20px;">baixar</a></p>
                </h2>
            </div>
            <div class="col-md-4">
                <h2>
                    <p class="bg-success">Matriz Curricular Habilitação Ciencias Humans e Sociais</p>
                    <p style="border: solid black 1px">2016 - 2018 <a
                                href="<?= PAF ?>/public/doc/ciencias_humanas_e_sociais.pdf"><img
                                    src="<?= PAF ?>/public/img/logo_pdf.png" style="width: 20px;">baixar</a></p>
                </h2>
            </div>
        </div>
    </div>
</div>

