<div class="container bg-info" >
    <div class="thumbnail">
        <h1><p class="text-center">Estágio Docente</p></h1>
    </div>
    <h3>
        <div class="thumbnail">
            <div class="container-fluid">
        
                <div class="col-md-8 thumbnail" style="border-top: solid black 1px;border-bottom: solid black 1px;">
                    <div class="">
                    <p class="bg-success"><h2><strong>Escolas Participantes</strong></h2></p>
                        <div class="">
                            <ul class="nav nav-pills nav-stacked" role="">
                                <li role="presentation" class="active"><a href="#eegv" aria-controls="home" role="tab" data-toggle="tab">Escola Estadual Guiomar de Vasconcelos</a></li>
                                <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Escola Municipal Professora Nazaré de Andrade Duarte</a></li>
                                <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Escola municipal Elza Bezerril Ribeiro</a></li>
                                <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
                            </ul>
                        </div>
                    </div>
                    
                </div>
                <div class="col-md-4 thumbnail">
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="eegv">
                    <img src="" class="media-object" style="width:350px;">
                        <div class="row">
                            <div class="col-xs-12">
                                <a class="thumbnail">
                                <img src="<?=PAF.DIR?>public/img/escola/eegv.jpg" alt="Escola Estadual Guiomar de Vasconcelos">
                                </a>
                            </div>
                        </div>
                        <p>Avenida João Gomes de Torres - s/n - Sertãozinho, Canguaretama - RN, 59190-000.</p>
                        <p>Ensino Fundamental e Médio</p>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="profile">
                        <div class="row">
                            <div class="col-xs-12">
                                <a class="thumbnail">
                                <img src="<?=PAF.DIR?>public/img/escola/eegv.jpg" alt="Escola Estadual Guiomar de Vasconcelos">
                                </a>
                            </div>
                        </div>
                        <p>Rua Tabelião Teófilo de Carvalho, 112, Cohab - Goianinha/RN.</p>
                        <p>Ensino Fundamental 2</p>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="messages">
                        <p>Rua Otávio Lima, Piquiri- Canguaretama, RN</p>
                        <p>Ensino fundamental I, II e EJA</p>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="settings">
                    4
                    </div>
                </div>
                </div>

            </div>
        </div>
    </h3>

</div>