<div class="container bg-info" >
    <div class="thumbnail">
        <h1><p class="text-center">Estágios Docente</p></h1>
    </div>
    <h3>
        <!--
        <div class="thumbnail">
            <div class="container-fluid">
                <div class="col-md-6 thumbnail" style="border-top: solid black 1px;border-bottom: solid black 1px;">
                    <div class="row">
                        <div class="col-xs-9">
                            <p class="bg-success"><h2><strong>Educação do Campo em pauta</strong></h2></p>
                            <p class="text-justify">O site <strong>Educação do Campo em Pauta</strong> foi criado pela
                                1° turma do curso LEDOC, durante a disciplina de Mídias Educacionais. O objetivo do
                                mesmo é trazer discursões referentes a Educação do Campo</p>

                        </div>
                        <div class="col-xs-3">
                            <a href="http://www2.ifrn.edu.br/leiai/Luiz/ed.docampoempauta/" target="_blank"><img
                                        src="img/ledoc.jornal_LOGO_FINAL.png" style="width: 100px;">Acessar</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        -->
    </h3>

</div>