<div class="modal fade" id="myModallogin" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="thumbnail center-block">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">Área de Acesso</h4>
                </div>
                <div class="modal-header">

                </div>
            </div>
            <div class="modal-body">
                <form class="login-form" action="" method="POST">
                    <div class="login-wrap" id="um" class="itens_menu">
                        <div class="container_login">
                            <div class="" style="height: 52px;">
                                <div class="input-group">
                                                <span class="input-group-addon"><span
                                                            class="glyphicon glyphicon-user"></span></i></span>
                                    <input type="text" class="form-control" placeholder="Matricula"
                                           name="matricula"
                                           autofocus style="height: 50px;">
                                </div>
                            </div>

                            <div class="" style="height: 52px;">
                                <div class="input-group">
                                                <span class="input-group-addon"><span
                                                            class="glyphicon glyphicon-lock"></span></span>
                                    <input type="password" class="form-control" placeholder="Senha"
                                           name="senha"
                                           style="height: 50px;">
                                </div>
                            </div>
                            <button class="btn-success btn-block btn-lg" type="submit">Acessar</button>
                        </div>
                    </div>
                </form>
                <button type="button" class="btn-success btn-block btn-lg" data-toggle="modal"
                        data-target="#myModalcadastro">Cadastrar
                </button>
            </div>
        </div>
    </div>
</div>
<!--====================== FIM DO MENU LATERAL =======================-->

<!--======================== ADICIONANDO JANELA MODAL PARA CADASTRO ==========================-->
<!--================================ JANELA MODAL PARA CADASTRO DO ADMINISTRADOR ======================================-->
<div class="modal fade" id="myModalcadastro" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="thumbnail center-block">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">Área de cadastro</h4>
                </div>
                <div class="modal-header">

                </div>
                <div class="modal-header">
                    <div class="">
                        <h4 class="bg-danger" id="exampleModalLabel">Atenção: </h4>
                    </div>
                    <div class="">
                        <h6 class="" id="exampleModalLabel">O cadastro é restrito para pessoas
                            autorizadas
                            pela instituição, caso não tenha autorização, não tente efetuá-lo.</h6>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    <div class="container-fluid thumbnail">
                        <div class="col-md-2 radio"><strong>Nome:</strong></div>
                        <div class="col-md-10"><input type="text" class="form-control" name="nome">
                        </div>
                    </div>
                    <div class="container-fluid thumbnail">
                        <div class="col-md-2 radio"><strong>E-mail:</strong></div>
                        <div class="col-md-10"><input type="email" class="form-control" name="email">
                        </div>
                    </div>
                    <div class="container-fluid thumbnail">
                        <div class="col-md-2 radio"><strong>Matricula:</strong></div>
                        <div class="col-md-10"><input type="text" class="form-control" name="matricul">
                        </div>
                    </div>

                    <div class="container-fluid thumbnail">
                        <div class="col-md-2 radio"><strong>Senha:</strong></div>
                        <div class="col-md-10"><input type="password" class="form-control" name="senh">
                        </div>
                    </div>
                    <div class="container-fluid thumbnail">
                        <div class="col-md-2 radio"><strong>Repita a senha:</strong></div>
                        <div class="col-md-10"><input type="password" class="form-control"
                                                      name="resenha">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!--======================== FIM DA JANELA MODAL =======================-->

<!--==================== FIM DA JANELA MODAL PARA CADASTRO ==============================-->

</div>
</div>
</div>


<div class="container" style="display: inline;" id="mydiv1">
    <div class="thumbnail">
        <h1><p class="text-center">COMUNICADOS</p></h1>
    </div>


    <!--Fim-->


    <div class="show container">
        <div class="container">

            <div class="col-sm-12">
                <div class="thumbnail">
                    <img src="" alt="...">
                    <div class="caption">
                        <h3></h3>
                        <p></p>
                    </div>
                </div>
            </div>

            <div class="pagina">
                <a href="index.php?pg=1"></a>
            </div>
        </div>
    </div>
</div>
</div>
