

<div class="container">
    <div class="thumbnail">
        <h1><p class="text-center">COMUNICADOS</p></h1>
    </div>

    <div class="show container">
        <div class="container">

            <div class="col-sm-12">
                <div class="thumbnail">
                    <img src="" alt="...">
                    <div class="caption">
                        <h3></h3>
                        <p></p>
                    </div>
                </div>
            </div>

            <div class="pagina">
                <a href="index.php?pg=1"></a>
            </div>
        </div>
    </div>
</div>
