-- MySQL Script generated by MySQL Workbench
-- Fri Oct 12 22:10:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ledoc_cang
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ledoc_cang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ledoc_cang` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `ledoc_cang` ;

-- -----------------------------------------------------
-- Table `ledoc_cang`.`ledoc_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ledoc_cang`.`ledoc_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(14) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `resenha` VARCHAR(30) NOT NULL,
  `updated_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ledoc_cang`.`ledoc_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ledoc_cang`.`ledoc_docente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ledoc_cang`.`ledoc_comunica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ledoc_cang`.`ledoc_comunica` (
  `id` INT NOT NULL,
  `id_ledoc_usuario` INT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `imagem` VARCHAR(200) NOT NULL,
  `texto` VARCHAR(500) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `ledoc_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ledoc_usuario_id`),
  INDEX `fk_ledoc_comunica_ledoc_usuario_idx` (`ledoc_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_ledoc_comunica_ledoc_usuario`
    FOREIGN KEY (`ledoc_usuario_id`)
    REFERENCES `ledoc_cang`.`ledoc_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*
CREATE TABLE ledoc_docente (
  id     smallint   not null auto_increment primary key,
  nome             varchar(100) not null,
  email varchar(40) not null
);


create table ledoc_usuario (
  matricula varchar(14) not null primary key,
  nome      varchar(50) not null,
  email     varchar(40) not null,
  senha     varchar(20) not null,
  resenha   varchar(20) not null,
  adm       varchar (3) not null,
  updated_at timestamp,
  created_at timestamp
);
INSERT into ledoc_usuario(matricula, nome, email, senha, resenha, adm, updated_at, created_at)value ('1234567', '','','','', 'sim','','');

create table ledoc_comunica (
  id int(7) not null auto_increment primary key,
  matricula varchar (14) not null,
  titulo  varchar(500) not null,
  imagem  varchar(200),
  texto  varchar(40000),
  updated_at timestamp,
  created_at timestamp
);

create table ledoc_postagem (
  codigo int(11) not null primary key,
  titulo  varchar(500) not null,
  imagem  varchar(200),
  video varchar (500),
  link varchar(500),
  documento varchar (500),
  data date
);

create table ledoc_projeto_participante (
  id int(11) not null primary key,
  nome varchar (40),
  periodo_referencia int(4)
);

create table ledoc_projeto (
  codigo int(11) not null primary key,
  titulo  varchar(500) not null,
  resumo varchar (500),
  documento varchar (500),
  data_inicio date,
  data_fim date,
  participantes int
);

create table ledoc_estagio_docente_escola (
  id int(11) not null primary key,
  nome  varchar(500) not null,
  endereco varchar (500),
  ensino varchar (500),
  imagem varchar(500)
);
*/

